In [1]:
import numpy as np

In [2]:
files = np.load('parameters.npz')

In [3]:
X = np.array([[1],[0],[1]])
y = np.array([[0],[0],[1]])

In [4]:
files['W1']

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [5]:
a1 = np.dot(files['W1'], X) + files['b1']

In [6]:
np.sum(a1), a1.sum()

(5.44766562448759, 5.44766562448759)

In [7]:
h1 = 1/(1 + np.exp(-a1))
h1

array([[0.82273938],
       [0.87894766],
       [0.87326546]])

In [8]:
h1.sum()

2.5749524957231924

In [9]:
a2 = np.dot(files['W2'], h1) + files['b2']
h2 = 1/(1 + np.exp(-a2))
a3 = np.dot(files['W3'], h2) + files['b3']

In [10]:
np.sum(a2), np.sum(h2), np.sum(a3)

(6.460166773282593, 2.63139309587371, 4.874920988265704)

In [11]:
def softmax(x):
    e_x = np.exp(x)  # Subtracting np.max(x) for numerical stability
    return e_x / e_x.sum()

In [12]:
output = softmax(a3)
output

array([[0.23691422],
       [0.33838847],
       [0.42469732]])

In [13]:
y * np.log(output)

array([[-0.        ],
       [-0.        ],
       [-0.85637856]])

In [14]:
def cross_entropy(y_true, y_pred):
  # Clip y_pred to avoid log(0) errors
  y_pred = np.clip(y_pred, 1e-10, 1 - 1e-10)
  # Compute the loss
  loss = -np.sum(y_true * np.log(y_pred))
  return loss

cross_entropy(y, output)


0.8563785622753882

In [15]:
# y -> actual labels 
# output -> predicted labels 
delta_a3 = -(y-output) 

In [17]:
delta_h2 = np.dot(np.transpose(files['W3']), delta_a3)

In [123]:
delta_a2 = np.multiply(delta_h2,np.multiply(a2,1-a2))

In [77]:
files['b2']- delta_a2

array([[0.45194361],
       [0.25464654],
       [0.59130436]])